# Generated by Django 5.0.3 on 2024-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidadBondis', models.IntegerField(max_length=100)),
                ('cantidadSubtes', models.IntegerField(max_length=100)),
                ('cantidadTrenes', models.IntegerField(max_length=100)),
            ],
        ),
    ]
