# Generated by Django 5.0.3 on 2024-03-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadBondis',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadSubtes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadTrenes',
            field=models.IntegerField(),
        ),
    ]
