# Generated by Django 5.0.3 on 2024-03-08 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0004_alter_estudiante_cantidadsubtes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadBondis',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadSubtes',
            field=models.CharField(max_length=100),
        ),
    ]
