# Generated by Django 3.2.12 on 2024-03-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0005_alter_estudiante_cantidadbondis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadBondis',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadSubtes',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadTrenes',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
