# Generated by Django 3.2.12 on 2024-03-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0006_auto_20240308_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadBondis',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadSubtes',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidadTrenes',
            field=models.PositiveIntegerField(default=100, null=True),
        ),
    ]
