# Generated by Django 3.2.12 on 2024-03-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0007_auto_20240308_0253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='cantidadBondis',
            new_name='cantidad_bondis',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='cantidadSubtes',
            new_name='cantidad_subtes',
        ),
        migrations.RenameField(
            model_name='estudiante',
            old_name='cantidadTrenes',
            new_name='cantidad_trenes',
        ),
    ]
