# Generated by Django 3.2.12 on 2024-03-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0008_auto_20240309_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='costo_total',
            field=models.FloatField(default=0),
        ),
    ]
