# Generated by Django 3.2.12 on 2024-03-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0009_estudiante_costo_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cantidad_bondis',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidad_subtes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cantidad_trenes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
