# Generated by Django 3.2.12 on 2024-03-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadoraBoletoEstudiantil', '0010_auto_20240309_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cantidad_dias',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='costo_total',
            field=models.IntegerField(default=0),
        ),
    ]
